singleInsightTip = There is already an Insight running.

# export && import
dlg.export.title=Export
dlg.export.desc=Please select a valid folder.

dlg.import.title=Import
dlg.import.desc=Please select a valid file.
dlg.import.msg.file.check=Please select an insight package file.

# memory monitor
dlg.memory.monitor=The memory usage reaches the threshold. Suggest ending recording.

# frame
dlg.frame.not.render=No rendering data available. Turn on the device screen for the Render Service to properly render frames.

# trace
dlg.trace.parse.failed=The recording file is too large and cannot be parsed. Restart a new recording session with shorter duration.