/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 */

export const computationCommunicationData: any = {
    top: [
        {
            rankId: '0',
            totalComputeTime: 1,
            totalCommunicationNotOverLapTime: 2,
            totalCommunicationTime: 3,
            totalFreeTime: 4,
            totalPureCommunicationTime: 5,
            ComputeTimeRatio: 20,
            CommunicationTimeRatio: 80,
        },
        {
            rankId: '1',
            totalComputeTime: 1,
            totalCommunicationNotOverLapTime: 2,
            totalCommunicationTime: 3,
            totalFreeTime: 4,
            totalPureCommunicationTime: 5,
            ComputeTimeRatio: 50,
            CommunicationTimeRatio: 50,
        },
        {
            rankId: '2',
            totalComputeTime: 1,
            totalCommunicationNotOverLapTime: 2,
            totalCommunicationTime: 3,
            totalFreeTime: 4,
            totalPureCommunicationTime: 5,
            ComputeTimeRatio: 80,
            CommunicationTimeRatio: 20,
        },
        {
            rankId: '3',
            totalComputeTime: 4,
            totalCommunicationNotOverLapTime: 2,
            totalCommunicationTime: 1,
            totalFreeTime: 9,
            totalPureCommunicationTime: 3,
            ComputeTimeRatio: 80,
            CommunicationTimeRatio: 20,
        },
    ],
    ComputingDetail: [
        {
            Name: 'AsStrided',
            Type: 'AsStrided',
            'Start Time': '2022-07-21 17:30:22',
            'Duration(us)': 7.06,
            'Wait Time(us)': 0,
            'Block Dim': 3,
            'Input Shapes': '8196;2;2;',
            'Input Data Types': 'INT64;INT64;INT64;INT64',
            'Input Formats': 'FORMAT_ND;FORMAT_ND;FORMAT_ND;FORMAT_ND',
            'Output Shapes': '4,2048',
            'Output Data Types': 'INT64',
            'Output Formats': 'FORMAT_ND',
        },
        {
            Name: 'OnesLike',
            Type: 'OnesLike',
            'Start Time': '2022-07-21 17:31:22',
            'Duration(us)': 11.86,
            'Wait Time(us)': 637.5599,
            'Block Dim': 48,
            'Input Shapes': '1,2048,2048',
            'Input Data Types': 'FLOAT',
            'Input Formats': 'FORMAT_ND',
            'Output Shapes': '1,2048,2048',
            'Output Data Types': 'FLOAT',
            'Output Formats': 'FORMAT_ND',
        },
    ],
    'Communication(OverLapped)Detail': [
        {
            'Communication Kernel': 'all_reduce1',
            'Start Time': '2022-07-21 17:30:22',
            'Total Durations(us)': 344.1,
            'Overlapped Durations(us)': 333.2,
            'Not Overlapped Durations(us)': 21.4,
        },
        {
            'Communication Kernel': 'all_reduce2',
            'Start Time': '2022-07-21 17:33:22',
            'Total Durations(us)': 211.1,
            'Overlapped Durations(us)': 100,
            'Not Overlapped Durations(us)': 30,
        },
    ],
    'Communication(Not OverLapped)Detail': [
        {
            'Communication Kernel': 'all_reduce1',
            'Start Time': '2022-07-21 17:30:22',
            'Total Durations(us)': 344.1,
            'Overlapped Durations(us)': 333.2,
            'Not Overlapped Durations(us)': 21.4,
        },
        {
            'Communication Kernel': 'all_reduce2',
            'Start Time': '2022-07-21 17:33:22',
            'Total Durations(us)': 211.1,
            'Overlapped Durations(us)': 100,
            'Not Overlapped Durations(us)': 30,
        },
    ],
    Computing: [
        {
            'Accelerator Core': 'AI CORE',
            'Accelerator Core Durations(us)': 500000,
            'Accelerator Core Utilization': '80%',
        },
        {
            'Accelerator Core': 'AI CPU',
            'Accelerator Core Durations(us)': 3222,
            'Accelerator Core Utilization': '20%',
        },
    ],
    'Communication(Not OverLapped)': [
        {
            'Transport Type': 'SDMA',
            'Total Durations(us)': 50000,
        },
        {
            'Transport Type': 'RDMA',
            'Total Durations(us)': 320,
        },
        {
            'Transport Type': 'LOCAL',
            'Total Durations(us)': 111,
        },
    ],
    'Communication(OverLapped)': [
        {
            'Transport Type': 'SDMA',
            'Total Durations(us)': 50000,
        },
        {
            'Transport Type': 'RDMA',
            'Total Durations(us)': 320,
        },
        {
            'Transport Type': 'LOCAL',
            'Total Durations(us)': 111,
        },
    ],
};

export const communicationAnalysisData: any = [
    {
        'Rank ID': '0',
        'Elapse Time(ms)': 0.3139404296875,
        'Transit Time(ms)': 0.022670000000000003,
        'Wait Time(ms)': 0.08212999999999997,
        'Synchronization Time(ms)': 0.02225,
        'Wait Time Ratio': 0.7837,
        'Synchronization Time Ratio': 0.4953,
        'Idle Time(ms)': 3,
        'Communication Bandwidth Info': {
            RDMA: {
                'Transit Size(MB)': 0,
                'Transit Time(ms)': 0,
                'Bandwidth(GB/s)': 0,
                'Bandwidth(Utilization)': 0.0,
                'Large Packet Ratio': 0,
                'Size Distribution': {},
            },
            HCCS: {
                'Transit Size(MB)': 0.0146484375,
                'Transit Time(ms)': 0.045090000000000005,
                'Bandwidth(GB/s)': 0.3249,
                'Bandwidth(Utilization)': 0.0181,
                'Large Packet Ratio': 0.0,
                'Size Distribution': {
                    0.0003662109375: 36.0,
                    0.000244140625: 6.0,
                },
            },
            PCIE: {
                'Transit Size(MB)': 0.0048828125,
                'Transit Time(ms)': 0.02176,
                'Bandwidth(GB/s)': 0.2244,
                'Bandwidth(Utilization)': 0.0112,
                'Large Packet Ratio': 0.0,
                'Size Distribution': {
                    0.000244140625: 2.0,
                    0.0003662109375: 12.0,
                },
            },
            SDMA: {
                'Transit Size(MB)': 0.01953125,
                'Transit Time(ms)': 0.06685,
                'Bandwidth(GB/s)': 0.2922,
                'Bandwidth(Utilization)': 0,
                'Large Packet Ratio': 0,
                'Size Distribution': {},
            },
        },
        'Slow Link Suggestion': 'SDMA communication takes most of the time, and is the dominated bottleneck. \nHCCS bandwidth is inefficient, and the bandwidth utilization is 0.02. Because it transported too many small packets, the big packet ratio is only 0.00. \n PCIE bandwidth is inefficient, and the bandwidth utilization is 0.01. Because it transported too many small packets, the big packet ratio is only 0.00. \n ',
    },
    {
        'Rank ID': '1',
        'Elapse Time(ms)': 0.261169921875,
        'Transit Time(ms)': 0.016100000000000003,
        'Wait Time(ms)': 0.012149999999999996,
        'Synchronization Time(ms)': 1e-05,
        'Wait Time Ratio': 0.4301,
        'Synchronization Time Ratio': 0.0006,
        'Communication Bandwidth Info': {
            RDMA: {
                'Transit Size(MB)': 0,
                'Transit Time(ms)': 0,
                'Bandwidth(GB/s)': 0,
                'Bandwidth(Utilization)': 0.0,
                'Large Packet Ratio': 0,
                'Size Distribution': {},
            },
            HCCS: {
                'Transit Size(MB)': 0.0146484375,
                'Transit Time(ms)': 0.04500000000000001,
                'Bandwidth(GB/s)': 0.3255,
                'Bandwidth(Utilization)': 0.0181,
                'Large Packet Ratio': 0.0,
                'Size Distribution': {
                    0.0003662109375: 36.0,
                    0.000244140625: 6.0,
                },
            },
            PCIE: {
                'Transit Size(MB)': 0.0048828125,
                'Transit Time(ms)': 0.02198,
                'Bandwidth(GB/s)': 0.2221,
                'Bandwidth(Utilization)': 0.0111,
                'Large Packet Ratio': 0.0,
                'Size Distribution': {
                    0.0003662109375: 12.0,
                    0.000244140625: 2.0,
                },
            },
            SDMA: {
                'Transit Size(MB)': 0.01953125,
                'Transit Time(ms)': 0.06698000000000001,
                'Bandwidth(GB/s)': 0.2916,
                'Bandwidth(Utilization)': 0,
                'Large Packet Ratio': 0,
                'Size Distribution': {},
            },
        },
        'Slow Link Suggestion': 'SDMA communication takes most of the time, and is the dominated bottleneck. \nHCCS bandwidth is inefficient, and the bandwidth utilization is 0.02. Because it transported too many small packets, the big packet ratio is only 0.00. \n PCIE bandwidth is inefficient, and the bandwidth utilization is 0.01. Because it transported too many small packets, the big packet ratio is only 0.00. \n ',
    },
    { 'Rank ID': '2', 'Elapse Time(ms)': 7, 'Transit Time(ms)': 9, 'Synchronization Time(ms)': 9, 'Wait Time(ms)': 9, 'Synchronization Time Ratio': 3.3, 'Wait Time Ratio': 4.5 },
    { 'Rank ID': '3', 'Elapse Time(ms)': 23.2, 'Transit Time(ms)': 26.4, 'Synchronization Time(ms)': 26.4, 'Wait Time(ms)': 26.4, 'Synchronization Time Ratio': 4.5, 'Wait Time Ratio': 6.3 },
    { 'Rank ID': '4', 'Elapse Time(ms)': 25.6, 'Transit Time(ms)': 28.7, 'Synchronization Time(ms)': 28.7, 'Wait Time(ms)': 28.7, 'Synchronization Time Ratio': 6.3, 'Wait Time Ratio': 18.8 },
    { 'Rank ID': '5', 'Elapse Time(ms)': 76.7, 'Transit Time(ms)': 70.7, 'Synchronization Time(ms)': 70.7, 'Wait Time(ms)': 70.7, 'Synchronization Time Ratio': 10.2, 'Wait Time Ratio': 6 },
    { 'Rank ID': '6', 'Elapse Time(ms)': 135.6, 'Transit Time(ms)': 175.6, 'Synchronization Time(ms)': 175.6, 'Wait Time(ms)': 175.6, 'Synchronization Time Ratio': 20.3, 'Wait Time Ratio': 2.3 },
];

export const OperatorDetailsData: any = [
    {
        'Rank ID': 1,
        'Operator Name': 'operator1',
        'Elapse Time(ms)': 62.9322,
        'Transit Time(ms)': 5,
        'Synchronization Time(ms)': 55,
        'Wait Time(ms)': 60,
        'Synchronization Time Ratio': 0.95,
        'Wait Time Ratio': 0.96,
        'Idle Time(ms)': 0.08,
    },
    {
        'Rank ID': 2,
        'Operator Name': 'operator2',
        'Elapse Time(ms)': 62.9322,
        'Transit Time(ms)': 5,
        'Synchronization Time(ms)': 55,
        'Wait Time(ms)': 60,
        'Synchronization Time Ratio': 0.95,
        'Wait Time Ratio': 0.96,
        'Idle Time(ms)': 0.08,
    },
    {
        'Rank ID': 3,
        'Operator Name': 'operator3',
        'Elapse Time(ms)': 62.9322,
        'Transit Time(ms)': 5,
        'Synchronization Time(ms)': 55,
        'Wait Time(ms)': 60,
        'Synchronization Time Ratio': 0.95,
        'Wait Time Ratio': 0.96,
        'Idle Time(ms)': 0.08,
    },
    {
        'Rank ID': 4,
        'Operator Name': 'operator4',
        'Elapse Time(ms)': 62.9322,
        'Transit Time(ms)': 5,
        'Synchronization Time(ms)': 55,
        'Wait Time(ms)': 60,
        'Synchronization Time Ratio': 0.95,
        'Wait Time Ratio': 0.96,
        'Idle Time(ms)': 0.08,
    },
];

export const communicationMatrixData = {

    '1_4': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.1691080000000076,
        'Transit Time(ms)': 4.511760000000004,
        'Bandwidth(GB/s)': 0.4808,
    },

    '2_3': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.1691080000000076,
        'Transit Time(ms)': 4.511760000000004,
        'Bandwidth(GB/s)': 0.4808,
    },

    '5_6': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.1691080000000076,
        'Transit Time(ms)': 4.511760000000004,
        'Bandwidth(GB/s)': 0.4808,
    },
    '7_4': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.1691080000000076,
        'Transit Time(ms)': 4.511760000000004,
        'Bandwidth(GB/s)': 0.4808,
    },
    '7_3': {
        'Transport Type': 1,
        'Transit Size(MB)': 2.1550080000000076,
        'Transit Time(ms)': 6.790580000000003,
        'Bandwidth(GB/s)': 0.3174,
    },
    '7_6': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.150400000000007,
        'Transit Time(ms)': 4.27529,
        'Bandwidth(GB/s)': 0.503,
    },
    '7_5': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.150400000000007,
        'Transit Time(ms)': 4.3023299999999995,
        'Bandwidth(GB/s)': 0.4998,
    },
    '7_7': {
        'Transport Type': 0,
        'Transit Size(MB)': 2.1691080000000076,
        'Transit Time(ms)': 6.790580000000003,
        'Bandwidth(GB/s)': 100,
    },
};
