/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 */

#ifndef DATA_INSIGHT_CORE_SCENE_ERROR_CODE_H
#define DATA_INSIGHT_CORE_SCENE_ERROR_CODE_H

namespace Dic {
namespace Scene {
const int ERR_CODE_TOKEN_CHECK = 0x1010;
const int ERR_CODE_SUB_TOKEN_CHECK = 0x1011;
enum class ErrorCode {
    UNKNOW_ERROR = 1001,
    REQUEST_NO_SUPPORT = 4001,
    REQUEST_TIME_OUT = 4002,
    REQUEST_PARAMS_ERROR = 4003,
    REQUEST_PARSE_ERROR = 4004,
    REQUEST_UNKNOW_ERROR = 4005,
    COMMAND_TIME_OUT = 5001,
    COMMAND_PARAMS_ERROR = 5002,
    PLUGIN_START_ERROR = 5003,
    PLUGIN_STOP_ERROR = 5004,
    FILE_PARSE_ERROR = 5005,
    SEARCH_DB_ERROR = 5006,
    DEVICE_CONNECT_ERROR = 5007
};
} // end of namespace Scene
} // end of namespace Dic

#endif // DATA_INSIGHT_CORE_SCENE_ERROR_CODE_H
