version: 2.0

params:
  - name: product
    value: cloudbuild2.0

env:
  label: Bitfun2Yellow_x64_vpc # 虚拟机标签，表示在哪台虚拟机执行，都写deveco_build
steps:
  PRE_BUILD:
    - checkout:
        path: server # 源码下载到子目录，命名请跟 clone下来的默认名称一致
    - codehub: 
        url: https://open.codehub.huawei.com/OpenSourceCenter/google/googletest
        tag: release-1.11.0
        path: server/third_party/googletest
    - codehub: 
        url: https://open.codehub.huawei.com/OpenSourceCenter/libuv/libuv
        tag: v1.44.2
        path: server/third_party/libuv
    - codehub: 
        url: https://open.codehub.huawei.com/OpenSourceCenter/www.sqlite.org/sqlite
        tag: 3.40.1
        path: server/third_party/sqlite_src
    - codehub: 
        url: https://open.codehub.huawei.com/OpenSourceCenter/uNetworking/uWebSockets
        tag: v20.10.0
        path: server/third_party/uWebSockets
    - codehub: 
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/uNetworking/uSockets.git
        tag: v0.8.1
        path: server/third_party/uSockets
    - codehub: 
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/nlohmann/json.git
        tag: v3.10.1
        path: server/third_party/json
    - codehub:
        url: https://szv-open.codehub.huawei.com/OpenSourceCenter/Tencent/rapidjson.git
        tag: 012be8528783cdbf4b7a9e64f78bd8f056b97e24
        path: server/third_party/rapidjson
  BUILD:
    - build_execute: # master用0.0.0.1-SNAPSHOT 和 0.0.0.1，  develop用0.0.0.2-SNAPSHOT，和 0.0.0.2
        command: |
          cd $WORKSPACE/server/third_party/sqlite
          mkdir include
          mkdir src
          cd ../sqlite_linux 
          cp sqlite3.h ../sqlite/include 
          cp sqlite3ext.h ../sqlite/include 
          cp sqlite3.c ../sqlite/src 
          cp shell.c ../sqlite/src 
          cd $WORKSPACE/server/third_party/ 
          if [ -d "json_modern_c++"];then 
          rm -rf json_modern_c++ 
          fi 
          mkdir -p json_modern_c++/include 
          cp json/single_include/nlohmann/json.hpp json_modern_c++/include 
          
          cd ${WORKSPACE}/server/build
          python build.py build --release
          
          cd ${WORKSPACE}/server/output
          cp -r linux_x86_64/bin bin
          cd bin
          tar zcvf ../../../server.tar.gz *
        check: true
  POST_BUILD:
    - get_build_metadata
    - artget:
        artifact_type: cloudartifact  # 仓库类型
        file_path: server.tar.gz
    - version_set #通常建议将这个插件一起配置上，主要用于上传versionset
    - get_build_metadata