version: 2.0

params:
  - name: product
    value: cloudbuild2.0
  - name: pluginVersion #intellij插件的构建版本号
    value: "6.0.RC3.1"
  - name: extensionVersion #vscode扩展的构建版本号
    value: "6.3.1"
  - name: serverBranch #server的分支
    value: "dev_ci"
  - name: artifactVersion #上传到云华产品仓的版本号
    value: "0.0.1"
  - name: taskName
    value: "buildOnlyWin"
  - name: cmc_username
    value: l30038348
  - name: cmc_password
    value: "encryption:ETMsDgAAAYnYMpUyABFBRVMvR0NNL05vUGFkZGluZwCAABAAEC8ardqF67F29Xmy5pD7ZjQAAAAtFru/1KUhg7mMADpYpSAqqfDSE9dmj2go+zjub861KlkHLagtsbVBsNBIyh6BABTaZnwewCbW2/Opj1OcBGyuPKlNng=="
  - name: offering
    value: BitFun Kernel
  - name: component_name
    value: Ascend Insight Plugin For VSCode And Intellij
  - name: version #下载的cmc的版本号
    value: 0.0.1
  - name: cmc_version #上传到cmc的版本号
    value: 0.0.1
  - name: snapshot #CMC快照版本，值为 Y 为上传快照版
    value: 'Y'
  - name: versionType
    value: Component


env:
  label: Bitfun2Yellow_x64_vpc # 虚拟机标签，表示在哪台虚拟机执行，都写deveco_build
buildflows:
  - condition: taskName == "buildOnlyWin"
    jobs:
      - job: buildWin
        build_ref: .cloudbuild/buildWin.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_win'
  - condition: taskName == "buildWinAndLinux"
    jobs:
      - job: buildWin
        build_ref: .cloudbuild/buildWin.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_win'
      - job: buildLinux
        build_ref: .cloudbuild/buildLinux.yml
        params:
          - name: buildVersion
            value: '${artifactVersion}_linux'
  - condition: taskName == "publish"
    jobs:
      - job: publish
        build_ref: .cloudbuild/buildPublish.yml
